apiVersion: v1
kind: Service
metadata:
  name: ants
  labels:
    app: ants
spec:
  type: LoadBalancer
  ports:
  - name: ants
    port: 8888
  selector:
    app: ants
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ants
  labels:
    chart: k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ants
    spec:
      containers:
      - name: ants
        image:  frodriguez4600/ants:9e057f4489f4
        imagePullPolicy: Always
        ports:
        - containerPort: 8888