apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls
spec:
  secretName: tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: facu-test.com
  dnsNames:
  - facu-test.com
  acme:
    config:
    - http01:
        ingress: web-nginx-ingress
      domains:
      - facu-test.com
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: www-tls
spec:
  secretName: www-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: www.facu-test.com
  dnsNames:
  - www.facu-test.com
  acme:
    config:
    - http01:
        ingress: web-nginx-ingress
      domains:
      - www.facu-test.com